name: krentileTest
version: 1.1.0
author: Albert Murciego Rico
description: Krentile sample project
homepage: https://github.com/redoxkun/krentile
environment:
  sdk: 1.8.0
dependencies:
  browser: any
  krentile:
    path: ../krentile
